### ISSUE TITLE
Include CONTRIBUTING file and CODE_OF_CONDUCT file #1

### ISSUE THREAD

**Issue by gpatchikoru** [angulardevelopment/emailjs#3]
I would like to update your repository with CONTRIBUTING file and CODE_OF_CONDUCT files so that everyone can get clear idea on creating forks and contributing effortless.

Can you please assign this task to me?

**Comment by sunny7899** [comment]
Go ahead @gpatchikoru

**Comment by gpatchikoru** [comment]
updated files  and raised the PR , please check it and let me know nay changes are required
